{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "problema1.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "mount_file_id": "1MDgk18i2n1wduLjC1gLrcSkMwOBC9E4I",
      "authorship_tag": "ABX9TyN1D+56lGKTN8uk0jpN6XFa",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/hectorcr2001/claselinux/blob/main/problema1.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import math\n",
        "\n",
        "def reescalarpos(x):\n",
        "  return x**1.496*10**(11)\n",
        "\n",
        "\n",
        "def modulo(x,y):\n",
        "  return math.sqrt(x*x+y*y)"
      ],
      "metadata": {
        "id": "YO0qoN0CIy_Q"
      },
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 341
        },
        "id": "oz-Ft7DxtCzq",
        "outputId": "2f6a46ee-b471-4516-926a-c14da0c29587"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Prefiere un punto de vista heliocentrista o geocentrista (escriba h o g)\n",
            "g\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:86: RuntimeWarning: invalid value encountered in double_scalars\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXwAAAD8CAYAAAB0IB+mAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAANT0lEQVR4nO3cYYjkd33H8ffHO1NpjKb0VpC706T00njYQtIlTRFqirZc8uDugUXuIFgleGAbKVWEFEuU+MiGWhCu1ZOKVdAYfSALntwDjQTEC7chNXgXItvTeheFrDHNk6Ax7bcPZtKdrneZf3Zndy/7fb/gYP7/+e3Mlx97752d2ZlUFZKk7e8VWz2AJGlzGHxJasLgS1ITBl+SmjD4ktSEwZekJqYGP8lnkzyZ5PuXuD5JPplkKcmjSW6c/ZiSpPUa8gj/c8CBF7n+VmDf+N9R4F/WP5YkadamBr+qHgR+/iJLDgGfr5FTwNVJXj+rASVJs7FzBrexGzg/cXxhfO6nqxcmOcrotwCuvPLKP7z++utncPeS1MfDDz/8s6qaW8vXziL4g1XVceA4wPz8fC0uLm7m3UvSy16S/1zr187ir3SeAPZOHO8Zn5MkXUZmEfwF4F3jv9a5GXimqn7t6RxJ0taa+pROki8BtwC7klwAPgK8EqCqPgWcAG4DloBngfds1LCSpLWbGvyqOjLl+gL+emYTSZI2hO+0laQmDL4kNWHwJakJgy9JTRh8SWrC4EtSEwZfkpow+JLUhMGXpCYMviQ1YfAlqQmDL0lNGHxJasLgS1ITBl+SmjD4ktSEwZekJgy+JDVh8CWpCYMvSU0YfElqwuBLUhMGX5KaMPiS1ITBl6QmDL4kNWHwJakJgy9JTRh8SWrC4EtSEwZfkpow+JLUhMGXpCYMviQ1YfAlqYlBwU9yIMnjSZaS3HWR69+Q5IEkjyR5NMltsx9VkrQeU4OfZAdwDLgV2A8cSbJ/1bK/B+6vqhuAw8A/z3pQSdL6DHmEfxOwVFXnquo54D7g0Ko1BbxmfPm1wE9mN6IkaRaGBH83cH7i+ML43KSPArcnuQCcAN5/sRtKcjTJYpLF5eXlNYwrSVqrWb1oewT4XFXtAW4DvpDk1267qo5X1XxVzc/Nzc3oriVJQwwJ/hPA3onjPeNzk+4A7geoqu8CrwJ2zWJASdJsDAn+aWBfkmuTXMHoRdmFVWt+DLwNIMmbGAXf52wk6TIyNfhV9TxwJ3ASeIzRX+OcSXJPkoPjZR8E3pvke8CXgHdXVW3U0JKkl27nkEVVdYLRi7GT5+6euHwWeMtsR5MkzZLvtJWkJgy+JDVh8CWpCYMvSU0YfElqwuBLUhMGX5KaMPiS1ITBl6QmDL4kNWHwJakJgy9JTRh8SWrC4EtSEwZfkpow+JLUhMGXpCYMviQ1YfAlqQmDL0lNGHxJasLgS1ITBl+SmjD4ktSEwZekJgy+JDVh8CWpCYMvSU0YfElqwuBLUhMGX5KaMPiS1ITBl6QmDL4kNTEo+EkOJHk8yVKSuy6x5p1JziY5k+SLsx1TkrReO6ctSLIDOAb8GXABOJ1koarOTqzZB/wd8JaqejrJ6zZqYEnS2gx5hH8TsFRV56rqOeA+4NCqNe8FjlXV0wBV9eRsx5QkrdeQ4O8Gzk8cXxifm3QdcF2S7yQ5leTAxW4oydEki0kWl5eX1zaxJGlNZvWi7U5gH3ALcAT4TJKrVy+qquNVNV9V83NzczO6a0nSEEOC/wSwd+J4z/jcpAvAQlX9qqp+CPyA0Q8ASdJlYkjwTwP7klyb5ArgMLCwas3XGD26J8kuRk/xnJvhnJKkdZoa/Kp6HrgTOAk8BtxfVWeS3JPk4HjZSeCpJGeBB4APVdVTGzW0JOmlS1VtyR3Pz8/X4uLilty3JL1cJXm4qubX8rW+01aSmjD4ktSEwZekJgy+JDVh8CWpCYMvSU0YfElqwuBLUhMGX5KaMPiS1ITBl6QmDL4kNWHwJakJgy9JTRh8SWrC4EtSEwZfkpow+JLUhMGXpCYMviQ1YfAlqQmDL0lNGHxJasLgS1ITBl+SmjD4ktSEwZekJgy+JDVh8CWpCYMvSU0YfElqwuBLUhMGX5KaMPiS1ITBl6QmBgU/yYEkjydZSnLXi6x7R5JKMj+7ESVJszA1+El2AMeAW4H9wJEk+y+y7irgb4CHZj2kJGn9hjzCvwlYqqpzVfUccB9w6CLrPgZ8HPjFDOeTJM3IkODvBs5PHF8Yn/s/SW4E9lbV11/shpIcTbKYZHF5efklDytJWrt1v2ib5BXAJ4APTltbVcerar6q5ufm5tZ715Kkl2BI8J8A9k4c7xmfe8FVwJuBbyf5EXAzsOALt5J0eRkS/NPAviTXJrkCOAwsvHBlVT1TVbuq6pqqugY4BRysqsUNmViStCZTg19VzwN3AieBx4D7q+pMknuSHNzoASVJs7FzyKKqOgGcWHXu7kusvWX9Y0mSZs132kpSEwZfkpow+JLUhMGXpCYMviQ1YfAlqQmDL0lNGHxJasLgS1ITBl+SmjD4ktSEwZekJgy+JDVh8CWpCYMvSU0YfElqwuBLUhMGX5KaMPiS1ITBl6QmDL4kNWHwJakJgy9JTRh8SWrC4EtSEwZfkpow+JLUhMGXpCYMviQ1YfAlqQmDL0lNGHxJasLgS1ITBl+SmhgU/CQHkjyeZCnJXRe5/gNJziZ5NMk3k7xx9qNKktZjavCT7ACOAbcC+4EjSfavWvYIMF9VfwB8FfiHWQ8qSVqfIY/wbwKWqupcVT0H3AccmlxQVQ9U1bPjw1PAntmOKUlaryHB3w2cnzi+MD53KXcA37jYFUmOJllMsri8vDx8SknSus30RdsktwPzwL0Xu76qjlfVfFXNz83NzfKuJUlT7Byw5glg78TxnvG5/yfJ24EPA2+tql/OZjxJ0qwMeYR/GtiX5NokVwCHgYXJBUluAD4NHKyqJ2c/piRpvaYGv6qeB+4ETgKPAfdX1Zkk9yQ5OF52L/Bq4CtJ/j3JwiVuTpK0RYY8pUNVnQBOrDp398Tlt894LknSjPlOW0lqwuBLUhMGX5KaMPiS1ITBl6QmDL4kNWHwJakJgy9JTRh8SWrC4EtSEwZfkpow+JLUhMGXpCYMviQ1YfAlqQmDL0lNGHxJasLgS1ITBl+SmjD4ktSEwZekJgy+JDVh8CWpCYMvSU0YfElqwuBLUhMGX5KaMPiS1ITBl6QmDL4kNWHwJakJgy9JTRh8SWrC4EtSEwZfkpoYFPwkB5I8nmQpyV0Xuf43knx5fP1DSa6Z9aCSpPWZGvwkO4BjwK3AfuBIkv2rlt0BPF1Vvwv8E/DxWQ8qSVqfIY/wbwKWqupcVT0H3AccWrXmEPBv48tfBd6WJLMbU5K0XjsHrNkNnJ84vgD80aXWVNXzSZ4Bfhv42eSiJEeBo+PDXyb5/lqG3oZ2sWqvGnMvVrgXK9yLFb+31i8cEvyZqarjwHGAJItVNb+Z93+5ci9WuBcr3IsV7sWKJItr/dohT+k8AeydON4zPnfRNUl2Aq8FnlrrUJKk2RsS/NPAviTXJrkCOAwsrFqzAPzl+PJfAN+qqprdmJKk9Zr6lM74Ofk7gZPADuCzVXUmyT3AYlUtAP8KfCHJEvBzRj8Upjm+jrm3G/dihXuxwr1Y4V6sWPNexAfiktSD77SVpCYMviQ1seHB92MZVgzYiw8kOZvk0STfTPLGrZhzM0zbi4l170hSSbbtn+QN2Ysk7xx/b5xJ8sXNnnGzDPg/8oYkDyR5ZPz/5LatmHOjJflskicv9V6ljHxyvE+PJrlx0A1X1Yb9Y/Qi738AvwNcAXwP2L9qzV8BnxpfPgx8eSNn2qp/A/fiT4HfHF9+X+e9GK+7CngQOAXMb/XcW/h9sQ94BPit8fHrtnruLdyL48D7xpf3Az/a6rk3aC/+BLgR+P4lrr8N+AYQ4GbgoSG3u9GP8P1YhhVT96KqHqiqZ8eHpxi952E7GvJ9AfAxRp/L9IvNHG6TDdmL9wLHquppgKp6cpNn3CxD9qKA14wvvxb4ySbOt2mq6kFGf/F4KYeAz9fIKeDqJK+fdrsbHfyLfSzD7kutqarngRc+lmG7GbIXk+5g9BN8O5q6F+NfUfdW1dc3c7AtMOT74jrguiTfSXIqyYFNm25zDdmLjwK3J7kAnADevzmjXXZeak+ATf5oBQ2T5HZgHnjrVs+yFZK8AvgE8O4tHuVysZPR0zq3MPqt78Ekv19V/7WlU22NI8Dnquofk/wxo/f/vLmq/merB3s52OhH+H4sw4ohe0GStwMfBg5W1S83abbNNm0vrgLeDHw7yY8YPUe5sE1fuB3yfXEBWKiqX1XVD4EfMPoBsN0M2Ys7gPsBquq7wKsYfbBaN4N6stpGB9+PZVgxdS+S3AB8mlHst+vztDBlL6rqmaraVVXXVNU1jF7POFhVa/7QqMvYkP8jX2P06J4kuxg9xXNuM4fcJEP24sfA2wCSvIlR8Jc3dcrLwwLwrvFf69wMPFNVP532RRv6lE5t3McyvOwM3It7gVcDXxm/bv3jqjq4ZUNvkIF70cLAvTgJ/HmSs8B/Ax+qqm33W/DAvfgg8Jkkf8voBdx3b8cHiEm+xOiH/K7x6xUfAV4JUFWfYvT6xW3AEvAs8J5Bt7sN90qSdBG+01aSmjD4ktSEwZekJgy+JDVh8CWpCYMvSU0YfElq4n8BzPZcum6w2goAAAAASUVORK5CYII=\n"
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ],
      "source": [
        "from re import X\n",
        "from numpy.lib.twodim_base import mask_indices\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import math\n",
        "\n",
        "\n",
        "# valores iniciales\n",
        "n=10000 #numero de iteraciones\n",
        "m=10 #numero de planetas\n",
        "h=0.1 #paso en el tiempo\n",
        "\n",
        "#inicializar las variables para el algoritmo (las de los ficheros ya están reescaladas)\n",
        "t=0\n",
        "ma=np.genfromtxt(\"/content/drive/MyDrive/Uni/Compu/masas.txt\") #masa\n",
        "rx=np.genfromtxt(\"/content/drive/MyDrive/Uni/Compu/distancias.txt\") #distancia al sol\n",
        "ry=np.zeros(m)\n",
        "vx=np.zeros(m)\n",
        "vy=np.genfromtxt(\"/content/drive/MyDrive/Uni/Compu/velocidad.txt\") #velocidad\n",
        "ax=np.zeros(m) #aceleracion\n",
        "ay=np.zeros(m)\n",
        "wx=np.zeros(m) #variable que se define en el algoritmo\n",
        "wy=np.zeros(m)\n",
        "\n",
        "#inicializar las variables para la comprobación de los periodos\n",
        "pt=np.genfromtxt(\"/content/drive/MyDrive/Uni/Compu/periodos.txt\")*365\n",
        "ps=np.zeros(m-1)\n",
        "psuma=np.zeros(m-1)\n",
        "cont=np.zeros(m-1)\n",
        "rya=np.zeros(m)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "print(\"Prefiere un punto de vista heliocentrista o geocentrista (escriba h o g)\")\n",
        "ref=input()\n",
        "if (ref==\"g\"):\n",
        "  rx=rx-1\n",
        "\n",
        "\n",
        "\n",
        "f = open(\"planets_data.txt\", \"w\")\n",
        "g= open(\"result_periodos.txt\",\"w\")\n",
        "#calcula las aceleraciones iniciales\n",
        "for i in range(m):\n",
        "    for j in range(m):\n",
        "      if (i != j):\n",
        "        ax[i]=ax[i]-ma[j]*(rx[i]-rx[j])/(modulo(rx[i]-rx[j],ry[i]-ry[j]))**3\n",
        "        ay[i]=ay[i]-ma[j]*(ry[i]-ry[j])/(modulo(rx[i]-rx[j],ry[i]-ry[j]))**3\n",
        "    #print(\"ax= \", ax[i], \"ay= \", ay[i])\n",
        "#recorre el algoritmo n veces\n",
        "for k in range(n):\n",
        "  for i in range(m):\n",
        "    rya[i]=ry[i]\n",
        "    rx[i]=rx[i]+h*vx[i]+(h*h*0.5)*ax[i]\n",
        "    ry[i]=ry[i]+h*vy[i]+(h*h*0.5)*ay[i]\n",
        "    wx[i]=vx[i]+(h*0.5)*ax[i]\n",
        "    wy[i]=vy[i]+(h*0.5)*ay[i]\n",
        "\n",
        "    \n",
        "    print(rx[i], \",\",ry[i], file=f) #escribe las posiciones en un archivo\n",
        "\n",
        "  print(\"\", file=f)\n",
        "  ax=np.zeros(m)\n",
        "  ay=np.zeros(m) \n",
        "  for i in range(m):\n",
        "    for j in range(m):\n",
        "      if (i != j):\n",
        "        ax[i]=ax[i]-ma[j]*(rx[i]-rx[j])/(modulo(rx[i]-rx[j],ry[i]-ry[j]))**3\n",
        "        ay[i]=ay[i]-ma[j]*(ry[i]-ry[j])/(modulo(rx[i]-rx[j],ry[i]-ry[j]))**3\n",
        "  for i in range(m):\n",
        "    vx[i]=wx[i]+(h*0.5)*(ax[i])\n",
        "    vy[i]=wy[i]+(h*0.5)*(ay[i])\n",
        "  \n",
        "  t=t+h\n",
        "\n",
        "  #comprobación periodos\n",
        "  for i in range(m-1):\n",
        "    if (rya[i+1]<0 & 0<ry[i+1]):\n",
        "      cont[i]=cont[i]+1\n",
        "      psuma[i]=psuma[i]+ps[i]\n",
        "      ps[i]=t-psuma[i]\n",
        "\n",
        "for i in range(m-1):\n",
        "  print(i,\" periodo medio\", psuma[i]/(cont[i]*24*3600*1.99*(10**(-7))),\"\\n\",\"periodo real: \",pt[i],\"\\n\", \"proporción: \",psuma[i]/(cont[i]*pt[i]*24*3600*1.99*(10**(-7))),\"\\n\",file=g)\n",
        "\n",
        "f.close()\n",
        "g.close()\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "dn7KO9S6c4Hy"
      },
      "outputs": [],
      "source": [
        "# ================================================================================\n",
        "# ANIMACION SISTEMA SOLAR\n",
        "#\n",
        "# Genera una animación a partir de un fichero de datos con las posiciones\n",
        "# de los planetas en diferentes instantes de tiempo.\n",
        "# \n",
        "# El fichero debe estructurarse de la siguiente forma:\n",
        "# \n",
        "#   x1_1, y1_1\n",
        "#   x2_1, y2_1\n",
        "#   x3_1, y3_1\n",
        "#   (...)\n",
        "#   xN_1, yN_1\n",
        "#   \n",
        "#   x1_2, y1_2\n",
        "#   x2_2, y2_2\n",
        "#   x3_2, y3_2\n",
        "#   (...)\n",
        "#   xN_2, yN_2\n",
        "#\n",
        "#   x1_3, y1_3\n",
        "#   x2_3, y2_3\n",
        "#   x3_3, y3_3\n",
        "#   (...)\n",
        "#   xN_3, yN_3\n",
        "#   \n",
        "#   (...)\n",
        "#\n",
        "# donde xi_j es la componente x del planeta i-ésimo en el instante de\n",
        "# tiempo j-ésimo, e yi_j lo mismo en la componente y. El programa asume que\n",
        "# el nº de planetas es siempre el mismo.\n",
        "# ¡OJO! Los datos están separados por comas.\n",
        "# \n",
        "# Si solo se especifica un instante de tiempo, se genera una imagen en pdf\n",
        "# en lugar de una animación\n",
        "#\n",
        "# Se puede configurar la animación cambiando el valor de las variables\n",
        "# de la sección \"Parámetros\"\n",
        "#\n",
        "# ================================================================================\n",
        "\n",
        "# Importa los módulos necesarios\n",
        "from matplotlib import pyplot as plt\n",
        "from matplotlib.animation import FuncAnimation\n",
        "from matplotlib.patches import Circle\n",
        "import numpy as np\n",
        "\n",
        "# Parámetros\n",
        "# ========================================\n",
        "file_in = \"planets_data.txt\" # Nombre del fichero de datos\n",
        "file_out = \"planetas\" # Nombre del fichero de salida (sin extensión)\n",
        "\n",
        "# Límites de los ejes X e Y\n",
        "x_min = -5\n",
        "x_max = 5\n",
        "y_min = -5\n",
        "y_max = 5\n",
        "\n",
        "interval = 100 # Tiempo entre fotogramas en milisegundos\n",
        "show_trail = True # Muestra la \"estela\" del planeta\n",
        "trail_width = 1 # Ancho de la estela\n",
        "save_to_file = True # False: muestra la animación por pantalla,\n",
        "                     # True: la guarda en un fichero\n",
        "dpi = 150 # Calidad del vídeo de salida (dots per inch)\n",
        "\n",
        "# Radio del planeta, en las mismas unidades que la posición\n",
        "# Puede ser un número (el radio de todos los planetas) o una lista con\n",
        "# el radio de cada uno\n",
        "planet_radius = 0.3\n",
        "#planet_radius = [0.5, 0.7, 1.1]\n",
        "\n",
        "\n",
        "# Lectura del fichero de datos\n",
        "# ========================================\n",
        "# Lee el fichero a una cadena de texto\n",
        "with open(file_in, \"r\") as f:\n",
        "    data_str = f.read()\n",
        "\n",
        "# Inicializa la lista con los datos de cada fotograma.\n",
        "# frames_data[j] contiene los datos del fotograma j-ésimo\n",
        "frames_data = list()\n",
        "\n",
        "# Itera sobre los bloques de texto separados por líneas vacías\n",
        "# (cada bloque corresponde a un instante de tiempo)\n",
        "for frame_data_str in data_str.split(\"\\n\\n\"):\n",
        "    # Inicializa la lista con la posición de cada planeta\n",
        "    frame_data = list()\n",
        "\n",
        "    # Itera sobre las líneas del bloque\n",
        "    # (cada línea da la posición de un planta)\n",
        "    for planet_pos_str in frame_data_str.split(\"\\n\"):\n",
        "        # Lee la componente x e y de la línea\n",
        "        planet_pos = np.fromstring(planet_pos_str, sep=\",\")\n",
        "        # Si la línea no está vacía, añade planet_pos a la lista de \n",
        "        # posiciones del fotograma\n",
        "        if planet_pos.size > 0:\n",
        "            frame_data.append(np.fromstring(planet_pos_str, sep=\",\"))\n",
        "\n",
        "    # Añade los datos de este fotograma a la lista\n",
        "    frames_data.append(frame_data)\n",
        "\n",
        "# El número de planetas es el número de líneas en cada bloque\n",
        "# Lo calculamos del primer bloque\n",
        "nplanets = len(frames_data[0])\n",
        "\n",
        "\n",
        "# Creación de la animación/gráfico\n",
        "# ========================================\n",
        "# Crea los objetos figure y axis\n",
        "fig, ax = plt.subplots()\n",
        "\n",
        "# Define el rango de los ejes\n",
        "ax.axis(\"equal\")  # Misma escala para ejes X e Y\n",
        "ax.set_xlim(x_min, x_max)\n",
        "ax.set_ylim(y_min, y_max)\n",
        "\n",
        "# Si solo se ha dado un radio para todos los planetas, conviértelo a una\n",
        "# lista con todos los elementos iguales\n",
        "if not hasattr(planet_radius, \"__iter__\"):\n",
        "    planet_radius = planet_radius*np.ones(nplanets)\n",
        "# En caso contrario, comprueba que el nº de radios coincide con el\n",
        "# nº de planetas y devuelve error en caso contrario\n",
        "else:\n",
        "    if not nplanets == len(planet_radius):\n",
        "        raise ValueError(\n",
        "                \"El número de radios especificados no coincide con el número \"\n",
        "                \"de planetas\")\n",
        "\n",
        "# Representa el primer fotograma\n",
        "# Pinta un punto en la posición de cada paneta y guarda el objeto asociado\n",
        "# al punto en una lista\n",
        "planet_points = list()\n",
        "planet_trails = list()\n",
        "for planet_pos, radius in zip(frames_data[0], planet_radius):\n",
        "    x, y = planet_pos\n",
        "    #planet_point, = ax.plot(x, y, \"o\", markersize=10)\n",
        "    planet_point = Circle((x, y), radius)\n",
        "    ax.add_artist(planet_point)\n",
        "    planet_points.append(planet_point)\n",
        "\n",
        "    # Inicializa las estelas (si especificado en los parámetros)\n",
        "    if show_trail:\n",
        "        planet_trail, = ax.plot(\n",
        "                x, y, \"-\", linewidth=trail_width,\n",
        "                color=planet_points[-1].get_facecolor())\n",
        "        planet_trails.append(planet_trail)\n",
        " \n",
        "# Función que actualiza la posición de los planetas en la animación \n",
        "def update(j_frame, frames_data, planet_points, planet_trails, show_trail):\n",
        "    # Actualiza la posición del correspondiente a cada planeta\n",
        "    for j_planet, planet_pos in enumerate(frames_data[j_frame]):\n",
        "        x, y = planet_pos\n",
        "        planet_points[j_planet].center = (x, y)\n",
        "\n",
        "        if show_trail:\n",
        "            xs_old, ys_old = planet_trails[j_planet].get_data()\n",
        "            xs_new = np.append(xs_old, x)\n",
        "            ys_new = np.append(ys_old, y)\n",
        "\n",
        "            planet_trails[j_planet].set_data(xs_new, ys_new)\n",
        "\n",
        "    return planet_points + planet_trails\n",
        "\n",
        "def init_anim():\n",
        "    # Clear trails\n",
        "    if show_trail:\n",
        "        for j_planet in range(nplanets):\n",
        "            planet_trails[j_planet].set_data(list(), list())\n",
        "\n",
        "    return planet_points + planet_trails\n",
        "\n",
        "# Calcula el nº de frames\n",
        "nframes = len(frames_data)\n",
        "\n",
        "# Si hay más de un instante de tiempo, genera la animación\n",
        "if nframes > 1:\n",
        "    # Info sobre FuncAnimation: https://matplotlib.org/stable/api/animation_api.html\n",
        "    animation = FuncAnimation(\n",
        "            fig, update, init_func=init_anim,\n",
        "            fargs=(frames_data, planet_points, planet_trails, show_trail),\n",
        "            frames=len(frames_data), blit=True, interval=interval)\n",
        "\n",
        "    # Muestra por pantalla o guarda según parámetros\n",
        "    if save_to_file:\n",
        "        animation.save(\"{}.mp4\".format(file_out), dpi=dpi)\n",
        "    else:\n",
        "        plt.show()\n",
        "# En caso contrario, muestra o guarda una imagen\n",
        "else:\n",
        "    # Muestra por pantalla o guarda según parámetros\n",
        "    if save_to_file:\n",
        "        fig.savefig(\"{}.pdf\".format(file_out))\n",
        "    else:\n",
        "        plt.show()"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        ""
      ],
      "metadata": {
        "id": "HKgESs8zksd0"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 265
        },
        "outputId": "4c7bedb4-e76e-4f58-da13-8144e1fd3c97",
        "id": "cDOk_7WkX17u"
      },
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 432x288 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAX8AAAD4CAYAAAAEhuazAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3dd3yV5f3/8dcn52QvssgkJIGEPYSAgDIUleWkbltwtKjVLu23RflZbets1dpvay2ofNW2LrSoFRXFAaisgOwwAmGHDEIWIfv6/ZEDDRBGknNyn/F5Ph55cM59xv25HiTvc5/rvu7rEmMMSimlfIuf1QUopZTqfBr+SinlgzT8lVLKB2n4K6WUD9LwV0opH2S3uoCWYmNjTVpamtVlKKXcxO5D1dj8hJSoYKtLcWurV68uMcbEteU1bhX+aWlp5OTkWF2GUspNHKlt4PrZy7h6cDI/GpNhdTluS0R2t/U12u2jlHJboYF25kzLZs7SnXybV2J1OV5Fw18p5daSuwTz5xsG87O31rK/7KjV5XgNDX+llNsb1TOWGaMzuOsfq6mpb7S6HK+g4a+U8gg/HJ1OWmwos+ZvRKel6TgNf6WURxARnvreADbuL+fNVXutLsfjafgrpTxGSICd5285jz8u3Mq2wkqry/FoGv5KKY/Ss2s4Myf15t7X13C0Tvv/20vDXynlca4bmkKfxAh+9+Fmq0vxWBr+SimPIyI8enV/lu0o4cP1B6wuxyNp+CulPFJ4kD9/uWkID7+/iQM6/r/NNPyVUh5rQEokt12Qxq/eWa/DP9tIw18p5dHuGtuDytoG/rm8zdPb+DQNf6WUR7Pb/HjmukE8+9k2dpUcsbocj6Hhr5TyeD27hvGTizO5f946Gpu0++dcaPgrpbzCraPS8LcJc7/Ot7oUj6Dhr5TyCn5+wpNTB/K3r/LYW1ptdTluT8NfKeU10mJD+eHoDB56Xyd/OxsNf6WUV5kxJoOCsho+XF9gdSluza2WcVTqdKpqGzhUVcuR2kaO1DVQVdtAdW0jDU1Npzw3JMBOaICN0EA7oYE2IoL9iQkNxOYnFlSuOpu/zY/Hpw7g7n+uZkxmHJEh/laX5JY0/JUlVuw8xGvLdjMsLYpbL0inoqaeXSVHyC85ws7iI+w6dISC8hqKK2sprKjBGIgODSA8yO4I9eaA97ed+OW10Rhq6po/IKrrGqmqbaDiaD1l1fVEhQYQFxZIfEQgqdEhpMWGkhYbSkZsKMldgrHb9IuwtxjaPYoJ/RJ4auEWHr9mgNXluCVxRr+YiMwFLgeKjDH9HdseAX4EFDue9qAx5qMzvU92drbRBdy9nzGGwb/7jPKj9QDEhAZwtL6R9BZhnBYTSmKXILqGBxEfEUhYoB2R9h+51zc2caiqjuLKWg5W1LD7UPMHTH7JEXaVVFN6pI5eCeH0T46gf1Ik/ZMj6Z0Qrh8IHqz8aD3jn1nMK7cNo39ypNXluJSIrDbGZLflNc468n8F+Cvw2knb/2SMedpJ+1BeQkSwt+iCeeJ7A7i0T3yHwv1s/G1+JEQGkRAZxABODYLKmnpyCyrZuL+clbtKeenrfAorahjaPYrz02MYnh7NwJTIU75pKPcVGezPfZdm8dv/bOLtO0e69PfLEzkl/I0xS0QkzRnvpXzD/902jNdX7GFYWjSX9U2wuhzCg/wZnh7N8PTo49sOVdWyalcpy3eW8v/e28j+w9WMyYpjfJ+ujMvqSlRogIUVq3Nxw7Bu/GvFbv6zvoArByVZXY5bcUq3D4Aj/D88qdvnVqACyAHuN8YcbuV1M4AZAKmpqUN379b5OZR7Kqqo4cutRXyeW8SyHYfonRjOFYOSmDwgkdiwQKvLU6exMr+Un7/5HYvuH0tIgHee5mxPt48rwz8eKAEM8Hsg0Rhz+5neQ/v8laeoqW/km7wSPlh3gC+2FDEkNYqrz0tiYr9EggNsVpenTnLv62vIiA3lvst6WV2KS7hV+J/rYy1p+CtPVF3XwGebC5n/3X7W7i3j6sHJfH9EKj27hltdmnLYX3aUKf+7lE9/PoauEUFWl+N07Ql/l529EpHEFnevATa6al9KWSkkwM5Vg5N55bbhfPiTCwkLtHPTiyu4YfYyPt5QoBONuYHkLsFcOySFP3++3epS3Iazhnq+AYwDYoFC4GHH/cE0d/vsAu40xpzxkjs98lfeoq6hiU83H+TFpflUHq3nzrEZXH1eMoF27RKyyuEjdVz8zFf8+8cXkB4banU5TmVpt48zaPgrb2OMYfnOUl5YvIOtByuYMaYHt5yfSpC/fghY4a9fbGfLwUr+evMQq0txKrfq9lFKNV/TMLJHDK/dPpy5tw5j2Y5DXPz0V7y1ag8NjadOTaFc6/YL01mZX8qGfeVWl2I5DX+lOkm/pEhemp7NX24ewr/X7Oey55bwycaDOvtkJwoJsPOTi3vy9KdbrS7Fchr+SnWyod2jeHPGCB6+oh/PfraVH7y8kryiSqvL8hnXD+vGtsJK1u0ts7oUS2n4K2UBEWFsVhwLfjqai3p35frZy3n8o1yqahusLs3rBdpt3Dkmg798kWd1KZbS8FfKQv42P+64MJ2FPx/Doao6JvxpCUu2FZ/9hapDbhyeyvp9ZWw64Lt9/xr+SrmBuPBAnrl+EE9MHcAD/97Ar95Zd3zWU+V8Qf42fjQ6g7/68NG/hr9SbmRMVhwLfzGGALsfE59bwtfbS6wuyWvdMiKVVbtK2Vbom+dbNPyVcjNhgXYevXoAf7x2EPfPW8sfF26hXoeFOl1IgJ3pI9N4aelOq0uxhIa/Um7qwsxYFvx0NBv2V3DD7GXsO1xtdUle55YR3flk40GKK2utLqXTafgr5cZiwwJ55dZhTOyfwNXPf6Mng50sOjSAywcl8Y/lvjeVvIa/Um7Oz0+YMaYHz988hPvnreOlpTv1wjAnuv2CdF5fsZua+karS+lUGv5KeYjzM2KY/+NR/HvNfu6ft87nwspVenYNY2BKF977br/VpXQqDX+lPEhKVAjv3j2K2vomps1dSXm1Dgd1hjsuTGfuN/k+9Y1Kw18pDxMcYOMvN51H/6RIrpv9LQXlR60uyeON6hFDQ5MhZ/cpK816LQ1/pTyQn5/w0OV9uHZoCte+sIztPjpW3VlEhJuHp/L6ij1Wl9JpNPyV8lAizSeC778si5tfWkFuQYXVJXm07w1JYVFuIYeP1FldSqfQ8FfKw00dksLDV/Rl2tyVbD6gHwDtFRUawPjeXXl3zT6rS+kUGv5KeYHLBybxyBX9mDZ3pU9PVtZRN5/fnddX7vGJE78a/kp5iSkDE/n9Vf2YPneVrg/QTsPSohBgtQ+c+HVK+IvIXBEpEpGNLbZFi8hnIrLd8W+UM/allDq9SQMSmTmpN9PnruJAmY4CaisRYeqQFN5b6/1j/p115P8KMPGkbTOBz40xmcDnjvtKKRe7dmgK00Z2Z/rclZRV+8bJS2e6clASC9YXUNfg3ZPpOSX8jTFLgNKTNl8FvOq4/SpwtTP2pZQ6uzvH9mBcrzjueDVHrwRuo27RIWTGh/PV1iKrS3EpV/b5xxtjChy3DwLxrT1JRGaISI6I5BQX66RVSjnLA5P6EB8RyIPzN/jECUxnuua8ZK/v+umUE76m+Tev1d8+Y8wcY0y2MSY7Li6uM8pRyif4+QlPXzeILQWVvOijc9a31+QBiSzdXuLVq6m5MvwLRSQRwPGvd3+HUsoNhQTYeXF6Ni8tzefLLfoneK4ig/0ZkRHD57mFVpfiMq4M/w+A6Y7b04H3XbgvpdRpJHcJ5m+3DOF/3lnHfh0BdM4m9U/gk40HrS7DZZw11PMNYBnQS0T2icgdwJPApSKyHbjEcV8pZYHstGh+ODqDn77xnS4JeY7G945n2Y5DVNc1WF2KSzhrtM9NxphEY4y/MSbFGPOyMeaQMWa8MSbTGHOJMebk0UBKqU40Y3QGYYF2nv1sm9WleITIEH8Gp3Zh8VbvHIiiV/gq5SP8/IRnrx/E/DX7+Xp7idXleIQJ/RL42Eu7fjT8lfIhMWGB/OHagfz63fVU1njvSBZnuaxvPF9uLaK2wfuulbBbXYBSzmaMoaC8hh3FVRSU1VBcVUtxZS3lR+upa2yirqGJxiZDoN2PYH8bwQE2okMDSIgMIjEyiJSoENJjQ/G3eeex0ZisOMZkxfL4R7k8MXWg1eW4ta4RQWTEhbF612FG9Yy1uhyn0vBXHu9A2VFydh9m9a5S1u4tI6+oipBAOz3jwkiOCiY2LJBu0SH0D/YnwO5HgM0Pu59Q29DE0fpGjtY1cOhIHRv2lfPZ5kL2HKpmf9lR0mND6Z0QTnZaNCMyoukRF4aIWN1cp3hwch8mPreUJduKGZOl19ecydisOBZvK9bwV8pqDY1NrNlTxqLcQhblFlJWXc/Q7lFkd4/i8kFJZHUNJzLEv0P7qKlvZHthFZsLylmRX8oLX+2gtqGRMVlxTOiXwJjMOIIDbE5qUecLD/LniakDeHD+BhbdN5Ygf89ti6uNzYpj1vwNPDC5j9WlOJW402Xf2dnZJicnx+oylJvaXljJO6v3Mf+7/cSEBXJp33gu6dOV/kmR+Pm5/oh8b2k1n+cWsnBTIRv3l3Nxn67cMKwbI9JjOmX/rnDP62voERfGfZdmWV2K22pobGLoo4v49BdjiI8IsrqcVonIamNMdpteo+Gv3Fljk2FRbiEvLtnJntJqpg5J4dqhyfTsGm5pXaVH6nh/7X7eXLmXmoZGfjCiOzcNTyU00LO+TBeUH2Xyn5fy3j0X0D0m1Opy3NY9r69hbFYc12d3s7qUVmn4K6/R0NjEO6v3MXvJTiKC7MwY04MJ/eKxu9lJWGMMa/eW8dLSfJbtPMT3R3TntlFpRIUGWF3aOfvbV3ms3nWYl28dZnUpbuvtVXtZvL2Y528eYnUprWpP+LvXX5LyecYYPtlYwGXPLeG9tft5YuoA3rvnAqYMTHS74IfmxT/OS43i+VuG8O7doyiqqGH8s4uZvXiHx0yl/MMLM8grruLbPB37fzoje8SwYmepV82O6n5/Tcpn5RVVcsPs5Ty3aDu/ubwvb/xoBCMyYjxmhE16bChPfm8g8+4aSc7uw4x/ZjELN7n/BUIBdj/uuzSLpxZu9apwc6aUqGACbEJ+yRGrS3EaDX9luZr6Rp79dCvX/X0ZUwYmsuCnoxnXq6vHhP7JesSF8eK0bP543UCe+ngLd/9zNUWVNVaXdUZXDEyirqGJhZu8dxbLjhARhqdHszLfe2ap0fBXlsorquSav31L7sFKPv7ZGKaPSsPmoSNnTjaqRywf/Ww06bGhTHpuKZ9sLDj7iyzi5yf8akIvnv50K41NevTfmuHpMRr+SjnDW6v2cP3s5Uwb2Z05PxhKQqR7DqPriCB/G7+a2JuXbx3Gowtyefj9jW47VcC4XnFEBNm9ehrjjhieHs0KDX+l2q++sYmH3tvIi0vzeWvGCG4anuqxXTznanC3Liz46WgKK2q57u/LKKpwv24gEeHucT15YXGe9v23okdcKDX1jRzwkjURNPxVpyqvrue2/1vF3sPVzP/xKDLjrR2v35kig/154ftDuKxvfHNXV0GF1SWdYnzvrtTWN/FN3iGrS3E7IsLgbl1Yv6/M6lKcQsNfdZriylpumLOMzPgwXp4+jPCgjk3B4IlEhHsvzuTXk3rz/ZdWuN3wSj8/4c6xPXhhcZ7VpbilASmRrNtXbnUZTqHhrzpFQflRbpi9jEn9E/nN5X295qRue105KInnbxnCT974jiXb3GuxkCsHJbG9sIrthZVWl+J2BqZEskHDX6lzU1RRww2zl3PDsG787JJMr+/fP1cjMmKY/YOh/OKttXy11X0WVw+w+3HDsG78a8Ueq0txOwOSm7t9vOGciIa/cqnyo/VMm7uS64amcOfYHlaX43ay06KZMy2b+95ex3d7DltdznE3Dk/lvbX7OVrnniOTrBIXHkhYoJ3dh6qtLqXDXB7+IrJLRDaIyFoR0Yl7fEhtQyM/ei2H89OjuffinlaX47aGdo/ij9cOZMY/VrvNFaTJXYIZmhrFh+sPWF2K2+mfHMmG/Z7f9dNZR/4XGWMGt3XiIeXZfvufzXQJ9ufhK/ppV89ZjO8Tz32XZnH7K6uocJPlFW8Y1o15q/dZXYbb6Z0QzjYvOB+i3T7KJd5cuYcVOw/xzPWDPHau+8520/BULugZw//MW+cWfcpje8WxrbCSgnLvGNfuLJnx4WwvrLK6jA7rjPA3wKcislpEZpz8oIjMEJEcEckpLnavUQ+qfXILKvjDwq3MmZbtk8M5O+Khy/tysKKWOUt2Wl0KgXYbE/om8OE6952WwgqZ8WFsK9Ij/3NxoTFmCDAJuEdExrR80BgzxxiTbYzJjovTtUQ9XW1DI794ay0PTOpNj7gwq8vxOIF2G8/ffB6zl+xky0HrLwK7YlASH6zTfv+W0mND2Xf4qNtO03GuXB7+xpj9jn+LgPnAcFfvU1nnuUXb6RYdwrVDU6wuxWOlRIXw64m9uP/tddQ3Nllay8geMRwoO8reUs8f3eIsgXYbKVHBbnNyvr1cGv4iEioi4cduA5cBG125T2WdrQcreXvVXp6YOkBP8HbQ9dndiA0LtLz7x+YnjM2Kc6vrENxBZtcwj+/3d/WRfzzwtYisA1YCC4wxn7h4n8oCxhge+WATPx2fSWxYoNXleDwR4dGr+/PS0p0cLLd2EriLenfliy0a/i2lxYSyx8O/Dbk0/I0xO40xgxw//Ywxj7lyf8o6H288yOHqOm45P9XqUrxGt+gQbj4/lac+2WJpHWMy41iZX6oXfLWQEh3CvsMa/srHNTYZnvl0Kw9O7uOW6+x6srvH9eTbHSWWzicTGeJP36QIVu7ynrnsO6pbVDB7Sz17CKz+paoO+3D9AbqEBDA6M9bqUrxOWKCdO8f04C9fbLe0jvPTY1jlRQuZdFS36BDt9lG+ranJ8L+fb+fnOmGby9w0PJU1e8osHfqZnRbFKj3yPy65SzAHy2s8eslLDX/VIUvzSgi027iwpx71u0pwgI3bL0yzdOTP0O5RbNhf7vFj250lyN9GVKg/B91wRbZzpeGvOuQfy3YzbWR3Pep3sRuHpbJocyFl1XWW7D88yJ/02FA2HbD+wjN3ER8R5JbLcZ4rDX/VbvvLjpKzu5QrBydZXYrXiw4N4KLeXXl3zX7LauifFKnh30JcWCDFlbVWl9FuGv6q3T5cd4BJ/RMICbBbXYpPuHFYKvNy9lq2/z6J4W657rBV4sIDKamy5puYM+hfrWq3jzYU8MsJvawuw6mqahv4ensJi3ILKT1Sx4DkSC7pE0/fpAjLl54cnh5NSVUd+SVHSI8N7fT990mM4H2d5+e4WA8/8tfwV+2yt7SavYePMjIjxupSOuybvBJueWlFq499saWIP3/+32GWIQE2lj84nggLZiu1+QkT+8fz8cYCfjyu8xfH6ZMUwdaDlTQ1GZ2mm+Yj/7wiz53iQcNftcuS7cWMzYrz6Iu6Ps8t5I5XT1xcbtbkPnx/RHeCA2xA87QVuQWV/HLeOjYXVFBd18jARz4FYPPvJnR6l9eEfgn86bNtloR/RJA/YYF2CitrSIwM7vT9u5u48ECW7ThkdRntpuGv2uXbHYcYl+WZU3AbY0h/4KPj9//flD78cHRGq88VEfomRfDRz0YDcKS2gX4PLwSg728W8pvL+3L7hemuL9phWFo0Ww5WcqS2gdDAzv/z7RYdwp5D1Rr+QGSwv9usutYennvYpixjjGHFzkOM7OF5XT4NjU3Hgz+5SzC7npxy2uBvTWignV1PTmHFg+MB+N2Hm5n856UuqbU1Qf42+idHkrPbmsXeU6ND2HvYs6c1cJawQDtVtQ1Wl9FueuSv2mzf4aPY/fxIiQqxupQ2McbQc9bHADx/8xCmDEw85TmlR+oY8vvPTvsem347gdBAO/ERQeQ/MZn0Bz5ic0EFU//2Df/+8QUuq72l89OjydlVylgLvnl1iwr2+GkNnCUsyE5VjeeGvx75qzbbdKCCPonhVpfRZseO+F+9ffgpwV9T30jazAVnDH6Afg8vJG3mAuobmxARdj05BYA1e8qY/13nLHbeLynCsiGXSV2CKSjTI3+A8EA7FRr+ypfkFlTQJzHC6jLa5NEPNwPwvSEpJxwxP/LBJgb/9lN6P9S2ZSYyZ33Mur1lAOQ/MRmAX7y1joZOWHmrd0IEuQXWrCEbHRrAYYuuMnY3YUF2qmq1z1/5kB3FVWTGe9b6vC99nQ/AM9cPOr5tW2Elr3y7i7Kj7fsDvur5b9hRXIWI8NUvxwEc71ZypdToEEqP1FnS3xwTFsChIxr+AMH+NuobjeVLbbaXhr9qs4PlnjXU757X1wCw+H/GnbA9NjTghPvz7hxxymtfnp7NtJHdT/ve459ZDEBai4uujHHtTI9+fkJilyBLul+iQgI4rOEPNI8EC7D5Udeg4a98REF5DUkeFP4L1hcA0D3mxKtihzy66Pjtb359EdfNXn78/q4npzBlYCJ3vJrDa8t2n/H902YuAODbmRcDzV1JrpYYGUSBBcs7Nnf7eG5Xh7PZbUJDo2dO66zhr9qsuLKWrhGesU7vsaPw4enRp31O/hOTueCpLwHoGh7IrienMPKJz49/aJyrpC7NH4ivnuXDwhniI4IsWds3yN9GTb1O63yMv82P+iY98m+ViEwUka0ikiciM129P+Va9Y1NNDQ1EWj3jOOGL7c2Lzz+2u3DT9h+7Gj97nEZJ0xHvXLWJQAnHFWveehS5t018oz7OVTVuXO8RAT5W9LnH2Dzo66xyeVdW57C7qdH/q0SERvwPDAJ6AvcJCJ9XblP5VpH6xsJCbB7zPz9v/tP8yifIH9bq4//emIfdhQ3z88ytHsU8N8PBoDeCeHkFVXx0HsbGXOGcfVDHV1InTUKKsjfxlELjsD9/ASbCA0evIKVM/nb/PSE72kMB/KMMTuNMXXAm8BVLt6ncqHaes856gfYdejsFyQdO2n77t2jTnmsuLKWJz7OZcvBSpZsKyY1+swXtk0ZkNC+Qtso2MLulwC7H7UeepLT2ew2z/0gdPUVvslAywnI9wHnt3yCiMwAZgCkpqa6uBzVUXY/z/1lP+bkvvLYsABKqurYW1pNt5PC/dCRuhOOsM92dWt6bOcMgZ0yMMGy/4ffXdUff5tnfPNztXvG9SQqpPNneHUGyw/hjDFzjDHZxpjsuDjPnCjMlwTYPWtoW++EU69E/spxHuCY9+5pnpZh9B+aT/o+dk3/Ex6vrmtkREY0Y7LOvk7xmj2dM+dOz67h9E6w5kK7a4emEGhvvRvN11w/rBtdQgLO/kQ35Orw3w90a3E/xbFNeahAux+1DY0ec8Lvwcl9AChpcUK2Z9f/Hp0//lHuCXMUNTUZbjn/1HH9y3eWsmRbyVn397LjYjKl3J2rw38VkCki6SISANwIfODifSoXstv8CAu0U+YhY71HZzYfrV/7wrfHtw1JjTp+e86SnSc8P+PB5vl/jk3ZcLJfXpZFa+e635wxgr+0WPRFKXfn0j5/Y0yDiNwLLARswFxjjOuvgFEu1TUiiKLKWqJC3f/r7rFRSS1P/J68CtUPXl7BrienHB/lkzZzAYvuG8OuJ6dgjKGytoFgfxt2PzlhHYCWEiODeOazbcfvF1bUEB8R5OzmKOU0Lp/S2RjzEdD6X4zySPERgRysqKFXK/3p7mj6yO68umw3K/NLW73Ya+n2EhasL2Dn45OPH/lf8uySM77nraPSeOXbXcfvRwb/96Rfl5DmFa+UcmeWn/BVnic1OpRdJUesLuOcPXJlPwCun73s+LYtv594wnPueX0NE55bwq4npzCx39mHa7YM/vwnJp8w5cE7d420ZJUtpdpCf0NVm/WKD2NboTVTCreHiDBrch8e+yiXS55dzKL7xhLkbyMjLpSdxf/9ENteVEXazAUMT49m+2OT8Lf5UV5dT11jExFB9uYPh5OuG/jrzecBcNHTXwHNHwSecgGc8m0a/qrNshLC+bCN895Y7UdjMnjso1zyiqp4aelOfjg6gy/uH3fC1bzHrMwvJfMcpma+dVQalw9MOv4e/3fbMA1+5TG020e1Wb+kSHILKjxqvD/AzsebR/A8uiCXpz7ZAjTP3pkUeeKJ2bNdxQsw766RPHxF3+PBP2VgIhf16urkipVyHQ1/1WaRwf6kxoSy8UC51aW0iZ+fsP2xSQC88NUO0mYuoKGxiW8fGM+ahy49/rwzXcUbYGteujEmNOD4yJ/JAxJ4/uYhri1eKScTd7pYJzs72+Tk5FhdhjoHj3ywifiIIO4e18PqUtrMGHPCkM3RmbG8cttwbI4hoMt2HOLuf60+fi3D90ekMrR7FFsPVnFZ33imtrhm4MVp2VzaN75zG6DUSURktTEmu02v0fBX7fHZ5kLmfp3PGzNOXf3KU2zYV84Vf/36hG2jesRw36VZ9IgLw9/ux5HaBr7JK+G+t9ed8vqdj08+5ZoBpayg4a86TU19I8MeXcTiX11EtAdc7HUm2woruexPZx7Xf8yFPWN55bZh2G3aY6rcR3vCX0f7qHYJ8rcxOiuWRZsLuX5Yt7O/wI1lxYez68kpADQ2GXILKth0oJyy6noy4sIYktqFmDDPWLlMqXOl4a/abcqAJP65fLfHh39LNj+hf3Ik/ZMjrS5FKZfS766q3S7tG8/2okryPehqX6VUMw1/1W4Bdj++NySFN1fusboUpVQbafirDrn5/FTmrd5nyWLiSqn20/BXHdI9JpQLe8byz+W7rS5FKdUGGv6qw+65qCcvf53P0TprFhRXSrWdhr/qsF4J4QxLi2LuN7qEoVKeQsNfOcXMiX14aelOiipqrC5FKXUONPyVU6TGhHDDsFQe/ziXvWeYGE0p5R40/JXT3DS8G/9ZW8DoP3zJg/M3WF2OUuoMXBb+IvKIiOwXkbWOn8mu2pdyD5sPVNDomCtq/pp9FlejlDoTV0/v8CdjzNMu3odyE0PTokiKDOJAeQ1XDEqyuhyl1Bno3D7KabqGB7Ho/rEUVdSSFhtqdTlKqTNwdZ//vSKyXkTmikhUa08QkRkikiMiOcXFxS4uR+DLd0gAAAhISURBVLlaSIBdg18pD9Ch+fxFZBGQ0MpDs4DlQAlggN8DicaY28/0fjqfv1JKtV2nz+dvjLnkXJ4nIi8CH3ZkX0oppZzHlaN9ElvcvQbY6Kp9KaWUahtXnvD9g4gMprnbZxdwpwv3pZRSqg1cFv7GmB+46r2VUkp1jF7hq5RSPkjDXymlfJCGv1JK+SANf6WU8kEa/kop5YM0/JVSygdp+CullA/S8FdKKR+k4a+UUj5Iw18ppXyQhr9SSvkgDX+llPJBGv5KKeWDNPyVUsoHafgrpZQP0vBXSikfpOGvlFI+SMNfKaV8kIa/Ukr5oA6Fv4hcJyKbRKRJRLJPeuwBEckTka0iMqFjZSqllHKmji7gvhGYCsxuuVFE+gI3Av2AJGCRiGQZYxo7uD+llFJO0KEjf2NMrjFmaysPXQW8aYypNcbkA3nA8I7sSymllPO4qs8/Gdjb4v4+x7ZTiMgMEckRkZzi4mIXlaOUUqqls3b7iMgiIKGVh2YZY97vaAHGmDnAHIDs7GzT0fdTSil1dmcNf2PMJe143/1Atxb3UxzblFJKuQFXdft8ANwoIoEikg5kAitdtC+llFJt1NGhnteIyD5gJLBARBYCGGM2AW8Dm4FPgHt0pI9SSrmPDg31NMbMB+af5rHHgMc68v5KKaVcQ6/wVUopH6Thr5RSPkjDXymlfJCGv1JK+SANf6WU8kEa/kop5YM0/JVSygdp+CullA/S8FdKKR+k4a+UUj5Iw18ppXyQhr9SSvkgDX+llPJBGv5KKeWDNPyVUsoHafgrpZQP0vBXSikfpOGvlFI+SMNfKaV8UEcXcL9ORDaJSJOIZLfYniYiR0VkrePn7x0vVSmllLN0aAF3YCMwFZjdymM7jDGDO/j+SimlXKBD4W+MyQUQEedUo5RSqlO4ss8/XUS+E5HFIjL6dE8SkRkikiMiOcXFxS4sRyml1DFnPfIXkUVAQisPzTLGvH+alxUAqcaYQyIyFHhPRPoZYypOfqIxZg4wByA7O9uce+lKKaXa66zhb4y5pK1vaoypBWodt1eLyA4gC8hpc4VKKaWcziXdPiISJyI2x+0MIBPY6Yp9KaWUaruODvW8RkT2ASOBBSKy0PHQGGC9iKwF3gHuMsaUdqxUpZRSztLR0T7zgfmtbH8XeLcj762UUsp19ApfpZTyQRr+SinlgzT8lVLKB2n4K6WUD9LwV0opH6Thr5RSPkjDXymlfJCGv1JK+SANf6WU8kEa/kop5YM0/JVSygdp+CullA/S8FdKKR+k4a+UUj5Iw18ppXyQhr9SSvkgDX+llPJBGv5KKeWDNPyVUsoHiTHG6hqOE5FKYKvVdbhQLFBidREupO3zbN7cPm9uG0AvY0x4W17QoQXcXWCrMSbb6iJcRURytH2eS9vnuby5bdDcvra+Rrt9lFLKB2n4K6WUD3K38J9jdQEupu3zbNo+z+XNbYN2tM+tTvgqpZTqHO525K+UUqoTaPgrpZQPcovwF5Hfi8h6EVkrIp+KSJJju4jI/4pInuPxIVbX2h4i8kcR2eJow3wR6dLisQcc7dsqIhOsrLO9ROQ6EdkkIk0ikn3SY97QvomO+vNEZKbV9XSUiMwVkSIR2dhiW7SIfCYi2x3/RllZY0eISDcR+VJENjt+L3/m2O4VbRSRIBFZKSLrHO37rWN7uoiscPyeviUiAWd8I2OM5T9ARIvbPwX+7rg9GfgYEGAEsMLqWtvZvssAu+P2U8BTjtt9gXVAIJAO7ABsVtfbjvb1AXoBXwHZLbZ7fPsAm6PuDCDA0Z6+VtfVwTaNAYYAG1ts+wMw03F75rHfUU/8ARKBIY7b4cA2x++iV7TRkYdhjtv+wApHPr4N3OjY/nfg7jO9j1sc+RtjKlrcDQWOnYW+CnjNNFsOdBGRxE4vsIOMMZ8aYxocd5cDKY7bVwFvGmNqjTH5QB4w3IoaO8IYk2uMae3KbG9o33Agzxiz0xhTB7xJc7s8ljFmCVB60uargFcdt18Fru7UopzIGFNgjFnjuF0J5ALJeEkbHXlY5bjr7/gxwMXAO47tZ22fW4Q/gIg8JiJ7gVuA3zg2JwN7Wzxtn2ObJ7ud5m8z4J3ta8kb2ucNbTgX8caYAsftg0C8lcU4i4ikAefRfHTsNW0UEZuIrAWKgM9o/nZa1uIg86y/p50W/iKySEQ2tvJzFYAxZpYxphvwL+DezqrLWc7WPsdzZgENNLfRo5xL+5R3MM39Bh4/BlxEwoB3gZ+f1Lvg8W00xjQaYwbT3IswHOjd1vfotLl9jDGXnONT/wV8BDwM7Ae6tXgsxbHN7ZytfSJyK3A5MN7xiwde1L7T8Jj2nYE3tOFcFIpIojGmwNG1WmR1QR0hIv40B/+/jDH/dmz2qjYCGGPKRORLYCTN3eJ2x9H/WX9P3aLbR0QyW9y9CtjiuP0BMM0x6mcEUN7ia5vHEJGJwK+AK40x1S0e+gC4UUQCRSQdyARWWlGji3hD+1YBmY6RFAHAjTS3y9t8AEx33J4OvG9hLR0iIgK8DOQaY55t8ZBXtFFE4o6NGBSRYOBSms9rfAlc63ja2dtn9Zlrx0Hwu8BGYD3wHyC5xVnt52nuz9pAi5EknvRD84nOvcBax8/fWzw2y9G+rcAkq2ttZ/uuobmPsRYoBBZ6Wfsm0zxiZAcwy+p6nNCeN4ACoN7x/3YHEAN8DmwHFgHRVtfZgfZdSHOXzvoWf3OTvaWNwEDgO0f7NgK/cWzPoPngKg+YBwSe6X10egellPJBbtHto5RSqnNp+CullA/S8FdKKR+k4a+UUj5Iw18ppXyQhr9SSvkgDX+llPJB/x+dpZ79r3bD3wAAAABJRU5ErkJggg==\n"
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ],
      "source": [
        "# ================================================================================\n",
        "# ANIMACION SISTEMA SOLAR\n",
        "#\n",
        "# Genera una animación a partir de un fichero de datos con las posiciones\n",
        "# de los planetas en diferentes instantes de tiempo.\n",
        "# \n",
        "# El fichero debe estructurarse de la siguiente forma:\n",
        "# \n",
        "#   x1_1, y1_1\n",
        "#   x2_1, y2_1\n",
        "#   x3_1, y3_1\n",
        "#   (...)\n",
        "#   xN_1, yN_1\n",
        "#   \n",
        "#   x1_2, y1_2\n",
        "#   x2_2, y2_2\n",
        "#   x3_2, y3_2\n",
        "#   (...)\n",
        "#   xN_2, yN_2\n",
        "#\n",
        "#   x1_3, y1_3\n",
        "#   x2_3, y2_3\n",
        "#   x3_3, y3_3\n",
        "#   (...)\n",
        "#   xN_3, yN_3\n",
        "#   \n",
        "#   (...)\n",
        "#\n",
        "# donde xi_j es la componente x del planeta i-ésimo en el instante de\n",
        "# tiempo j-ésimo, e yi_j lo mismo en la componente y. El programa asume que\n",
        "# el nº de planetas es siempre el mismo.\n",
        "# ¡OJO! Los datos están separados por comas.\n",
        "# \n",
        "# Si solo se especifica un instante de tiempo, se genera una imagen en pdf\n",
        "# en lugar de una animación\n",
        "#\n",
        "# Se puede configurar la animación cambiando el valor de las variables\n",
        "# de la sección \"Parámetros\"\n",
        "#\n",
        "# ================================================================================\n",
        "\n",
        "# Importa los módulos necesarios\n",
        "from matplotlib import pyplot as plt\n",
        "from matplotlib.animation import FuncAnimation\n",
        "from matplotlib.patches import Circle\n",
        "import numpy as np\n",
        "\n",
        "# Parámetros\n",
        "# ========================================\n",
        "file_in = \"planets_data.txt\" # Nombre del fichero de datos\n",
        "file_out = \"planetas_lejos\" # Nombre del fichero de salida (sin extensión)\n",
        "\n",
        "# Límites de los ejes X e Y\n",
        "x_min = -30\n",
        "x_max = 30\n",
        "y_min = -30\n",
        "y_max = 30\n",
        "\n",
        "interval = 100 # Tiempo entre fotogramas en milisegundos\n",
        "show_trail = True # Muestra la \"estela\" del planeta\n",
        "trail_width = 1 # Ancho de la estela\n",
        "save_to_file = True # False: muestra la animación por pantalla,\n",
        "                     # True: la guarda en un fichero\n",
        "dpi = 150 # Calidad del vídeo de salida (dots per inch)\n",
        "\n",
        "# Radio del planeta, en las mismas unidades que la posición\n",
        "# Puede ser un número (el radio de todos los planetas) o una lista con\n",
        "# el radio de cada uno\n",
        "planet_radius = 0.3\n",
        "#planet_radius = [0.5, 0.7, 1.1]\n",
        "\n",
        "\n",
        "# Lectura del fichero de datos\n",
        "# ========================================\n",
        "# Lee el fichero a una cadena de texto\n",
        "with open(file_in, \"r\") as f:\n",
        "    data_str = f.read()\n",
        "\n",
        "# Inicializa la lista con los datos de cada fotograma.\n",
        "# frames_data[j] contiene los datos del fotograma j-ésimo\n",
        "frames_data = list()\n",
        "\n",
        "# Itera sobre los bloques de texto separados por líneas vacías\n",
        "# (cada bloque corresponde a un instante de tiempo)\n",
        "for frame_data_str in data_str.split(\"\\n\\n\"):\n",
        "    # Inicializa la lista con la posición de cada planeta\n",
        "    frame_data = list()\n",
        "\n",
        "    # Itera sobre las líneas del bloque\n",
        "    # (cada línea da la posición de un planta)\n",
        "    for planet_pos_str in frame_data_str.split(\"\\n\"):\n",
        "        # Lee la componente x e y de la línea\n",
        "        planet_pos = np.fromstring(planet_pos_str, sep=\",\")\n",
        "        # Si la línea no está vacía, añade planet_pos a la lista de \n",
        "        # posiciones del fotograma\n",
        "        if planet_pos.size > 0:\n",
        "            frame_data.append(np.fromstring(planet_pos_str, sep=\",\"))\n",
        "\n",
        "    # Añade los datos de este fotograma a la lista\n",
        "    frames_data.append(frame_data)\n",
        "\n",
        "# El número de planetas es el número de líneas en cada bloque\n",
        "# Lo calculamos del primer bloque\n",
        "nplanets = len(frames_data[0])\n",
        "\n",
        "\n",
        "# Creación de la animación/gráfico\n",
        "# ========================================\n",
        "# Crea los objetos figure y axis\n",
        "fig, ax = plt.subplots()\n",
        "\n",
        "# Define el rango de los ejes\n",
        "ax.axis(\"equal\")  # Misma escala para ejes X e Y\n",
        "ax.set_xlim(x_min, x_max)\n",
        "ax.set_ylim(y_min, y_max)\n",
        "\n",
        "# Si solo se ha dado un radio para todos los planetas, conviértelo a una\n",
        "# lista con todos los elementos iguales\n",
        "if not hasattr(planet_radius, \"__iter__\"):\n",
        "    planet_radius = planet_radius*np.ones(nplanets)\n",
        "# En caso contrario, comprueba que el nº de radios coincide con el\n",
        "# nº de planetas y devuelve error en caso contrario\n",
        "else:\n",
        "    if not nplanets == len(planet_radius):\n",
        "        raise ValueError(\n",
        "                \"El número de radios especificados no coincide con el número \"\n",
        "                \"de planetas\")\n",
        "\n",
        "# Representa el primer fotograma\n",
        "# Pinta un punto en la posición de cada paneta y guarda el objeto asociado\n",
        "# al punto en una lista\n",
        "planet_points = list()\n",
        "planet_trails = list()\n",
        "for planet_pos, radius in zip(frames_data[0], planet_radius):\n",
        "    x, y = planet_pos\n",
        "    #planet_point, = ax.plot(x, y, \"o\", markersize=10)\n",
        "    planet_point = Circle((x, y), radius)\n",
        "    ax.add_artist(planet_point)\n",
        "    planet_points.append(planet_point)\n",
        "\n",
        "    # Inicializa las estelas (si especificado en los parámetros)\n",
        "    if show_trail:\n",
        "        planet_trail, = ax.plot(\n",
        "                x, y, \"-\", linewidth=trail_width,\n",
        "                color=planet_points[-1].get_facecolor())\n",
        "        planet_trails.append(planet_trail)\n",
        " \n",
        "# Función que actualiza la posición de los planetas en la animación \n",
        "def update(j_frame, frames_data, planet_points, planet_trails, show_trail):\n",
        "    # Actualiza la posición del correspondiente a cada planeta\n",
        "    for j_planet, planet_pos in enumerate(frames_data[j_frame]):\n",
        "        x, y = planet_pos\n",
        "        planet_points[j_planet].center = (x, y)\n",
        "\n",
        "        if show_trail:\n",
        "            xs_old, ys_old = planet_trails[j_planet].get_data()\n",
        "            xs_new = np.append(xs_old, x)\n",
        "            ys_new = np.append(ys_old, y)\n",
        "\n",
        "            planet_trails[j_planet].set_data(xs_new, ys_new)\n",
        "\n",
        "    return planet_points + planet_trails\n",
        "\n",
        "def init_anim():\n",
        "    # Clear trails\n",
        "    if show_trail:\n",
        "        for j_planet in range(nplanets):\n",
        "            planet_trails[j_planet].set_data(list(), list())\n",
        "\n",
        "    return planet_points + planet_trails\n",
        "\n",
        "# Calcula el nº de frames\n",
        "nframes = len(frames_data)\n",
        "\n",
        "# Si hay más de un instante de tiempo, genera la animación\n",
        "if nframes > 1:\n",
        "    # Info sobre FuncAnimation: https://matplotlib.org/stable/api/animation_api.html\n",
        "    animation = FuncAnimation(\n",
        "            fig, update, init_func=init_anim,\n",
        "            fargs=(frames_data, planet_points, planet_trails, show_trail),\n",
        "            frames=len(frames_data), blit=True, interval=interval)\n",
        "\n",
        "    # Muestra por pantalla o guarda según parámetros\n",
        "    if save_to_file:\n",
        "        animation.save(\"{}.mp4\".format(file_out), dpi=dpi)\n",
        "    else:\n",
        "        plt.show()\n",
        "# En caso contrario, muestra o guarda una imagen\n",
        "else:\n",
        "    # Muestra por pantalla o guarda según parámetros\n",
        "    if save_to_file:\n",
        "        fig.savefig(\"{}.pdf\".format(file_out))\n",
        "    else:\n",
        "        plt.show()"
      ]
    }
  ]
}